const constants = {
  "BRAND_FILMS": 0,
  "CORPORATE_FILMS": "1",
  "PRODUCT_VIDEOS": "2",
  "EXPLAINER_VIDEOS": "3",
  "SOCIAL_MEDIA_CONTENT": "4",
  "EVENT_COVERAGE": "5",
  "TESTIMONIAL_VIDEOS": "6",
  "TRAINING_VIDEOS": "7",
  "ANIMATION_AND_MOTION_GRAPHICS": "8",
  "DRONE_VIDEOGRAPHY": "9"
};